import "./globals.css";
import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import Sidenav from "@/components/Sidenav";
import CartSlider from "@/components/CartSlider";
import AddNewItem from "@/components/AddNewItem";
import ItemCart from "@/components/ItemCart";

const quicksand = Quicksand({
  weight: ["600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Shoppingify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${quicksand.className} flex`}>
        {/* sidenav section */}
        <Sidenav />
        <main className="scrollArea relative w-screen h-screen overflow-scroll">
          {children}
          <CartSlider />
          <AddNewItem />
          <ItemCart />
        </main>
      </body>
    </html>
  );
}
